shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1

packages:
  - apps/*
  - apps/apis/*
  - packages/*

overrides:
  vite: npm:rolldown-vite@7.2.5

catalogs:
  api:
    '@asteasolutions/zod-to-openapi': 8.4.0
    '@hono/node-server': 1.19.6
    '@hono/zod-openapi': 1.2.0
    '@scalar/hono-api-reference': 0.9.32
    '@types/pg': 8.16.0
    drizzle-kit: 0.31.8
    drizzle-orm: 0.45.1
    drizzle-zod: 0.8.3
    hono: 4.11.3
    hono-pino: 0.10.3
    pg: 8.16.3
    pino: 10.1.1
    pino-pretty: 13.1.3

  frontend:
    '@tailwindcss/vite': 4.1.18
    class-variance-authority: 0.7.1
    clsx: 2.1.1
    tailwind-merge: 3.4.0
    tailwindcss: 4.1.18
    tw-animate-css: 1.4.0
    xior: 0.8.3

  linting:
    '@antfu/eslint-config': 6.7.3
    '@eslint-react/eslint-plugin': 2.5.5
    '@tanstack/eslint-plugin-query': 5.91.2
    eslint: 9.39.2
    eslint-plugin-drizzle: 0.2.3
    eslint-plugin-format: 1.2.0
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-react-refresh: 0.4.26
    eslint-plugin-tailwindcss: 4.0.0-beta.0

  react:
    '@hookform/resolvers': 5.2.2
    '@radix-ui/react-dialog': 1.1.15
    '@radix-ui/react-label': 2.1.8
    '@radix-ui/react-separator': 1.1.8
    '@tanstack/react-query': 5.90.16
    '@tanstack/react-query-devtools': 5.91.2
    '@tanstack/react-router': 1.147.3
    '@tanstack/react-router-devtools': 1.149.0
    '@tanstack/router-plugin': 1.149.0
    '@types/react': 19.2.5
    '@types/react-dom': 19.2.3
    '@vitejs/plugin-react': 5.1.1
    babel-plugin-react-compiler: 1.0.0
    lucide-react: 0.562.0
    react: 19.2.0
    react-dom: 19.2.0
    react-hook-form: 7.71.1
    vite: npm:rolldown-vite@7.2.5
    zustand: 5.0.10

  shared:
    dotenv: 17.2.3
    dotenv-expand: 12.0.3
    zod: 4.3.5

  tooling:
    '@rollup/plugin-commonjs': 29.0.0
    '@rollup/plugin-json': 6.1.0
    '@rollup/plugin-node-resolve': 16.0.3
    '@rollup/plugin-terser': 0.4.4
    '@rollup/plugin-typescript': 12.3.0
    '@types/node': 25.0.3
    husky: 9.1.7
    lint-staged: 16.2.7
    rollup: 4.55.1
    rollup-plugin-dts: 6.3.0
    tslib: 2.8.1
    tsx: 4.21.0
    typescript: 5.9.3
