shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'apps/*'
  - 'apps/apis/*'
  - 'packages/*'

catalogs:
  api:
    '@hono/node-server': 1.19.6
    '@hono/zod-openapi': 1.2.0
    hono: 4.11.3

  linting:
    '@antfu/eslint-config': 6.7.3
    eslint: 9.39.2
    eslint-plugin-drizzle: 0.2.3
    eslint-plugin-format: 1.2.0

  shared:
    zod: 4.3.5

  tooling:
    '@rollup/plugin-commonjs': 29.0.0
    '@rollup/plugin-node-resolve': 16.0.3
    '@rollup/plugin-terser': 0.4.4
    '@rollup/plugin-typescript': 12.3.0
    '@types/node': 25.0.3
    husky: 9.1.7
    lint-staged: 16.2.7
    rollup: 4.55.1
    tslib: 2.8.1
    tsx: 4.21.0
    typescript: 5.9.3
