shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'apps/*'
  - 'apps/apis/*'
  - 'packages/*'

catalogs:
  api:
    '@hono/node-server': 1.19.6
    '@hono/zod-openapi': 1.2.0
    '@scalar/hono-api-reference': 0.9.32
    hono: 4.11.3
    hono-pino: 0.10.3
    pino: 10.1.1
    pino-pretty: 13.1.3

  linting:
    '@antfu/eslint-config': 6.7.3
    eslint: 9.39.2
    eslint-plugin-drizzle: 0.2.3
    eslint-plugin-format: 1.2.0

  shared:
    dotenv: 17.2.3
    dotenv-expand: 12.0.3
    zod: 4.3.5

  tooling:
    '@rollup/plugin-commonjs': 29.0.0
    '@rollup/plugin-json': 6.1.0
    '@rollup/plugin-node-resolve': 16.0.3
    '@rollup/plugin-terser': 0.4.4
    '@rollup/plugin-typescript': 12.3.0
    '@types/node': 25.0.3
    husky: 9.1.7
    lint-staged: 16.2.7
    rollup: 4.55.1
    rollup-plugin-dts: 6.3.0
    tslib: 2.8.1
    tsx: 4.21.0
    typescript: 5.9.3
