shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'apps/*'
  - 'apps/apis/*'
  - 'packages/*'

catalogs:
  api:
    '@hono/node-server': 1.19.6
    hono: 4.11.3

  linting:
    '@antfu/eslint-config': 6.7.3
    eslint: 9.39.2
    eslint-plugin-drizzle: 0.2.3
    eslint-plugin-format: 1.2.0

  tooling:
    '@types/node': 25.0.3
    husky: 9.1.7
    lint-staged: 16.2.7
    tsx: 4.21.0
    typescript: 5.9.3
